<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionRepository extends EntityRepository
{
    public function getCollectionInfo(){
        $qb = $this->createQueryBuilder('u');
        $qb->select($qb->expr()->count('u.title'), 'u.modification');
        $qb->orderBy('u.modification', 'DESC');



        return $qb->getQuery()->getArrayResult();
    }
}
