<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTagCount(){
        $qb = $this->createQueryBuilder('u');
        $qb->select($qb->expr()->count('u.name'), 'u.name');

        $qb->groupBy('u.name');

        return $qb->getQuery()->getArrayResult();
    }
}
