liip_imagine:
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                relative_resize: { heighten: 140 }
        item_list:
            quality: 75
            filters:
                relative_resize: { heighten: 300 }
        item_detail:
            quality: 90
            filters:
                relative_resize: { heighten: 400 }
        item_view:
            quality: 90
            filters:
                relative_resize: { heighten: 600 }
        avatar_list:
            quality: 75
            filters:
                relative_resize: { heighten: 40 }